import { CONFIDENCE_THRESHOLDS } from '../../types';
import type { ParsedIntent, TxStep, RiskLevel } from '../../types';

export interface RiskAssessment {
  riskLevel: RiskLevel;
  warnings: string[];
}

/**
 * Pure function to evaluate the risk of a proposed action.
 * Maps agent confidence and intent ambiguities into the strict RiskLevel scale.
 */
export function evaluateRisk(
  intent: ParsedIntent,
  steps: TxStep[],
  finalConfidence: number
): RiskAssessment {
  let riskLevel: RiskLevel = 'low';
  const warnings: string[] = [];

  // 1. Confidence heuristics
  if (finalConfidence < CONFIDENCE_THRESHOLDS.BLOCK_EXECUTION) {
    riskLevel = 'high';
    warnings.push(`AI confidence is critically low (${Math.round(finalConfidence * 100)}%). Execution should be blocked.`);
  } else if (finalConfidence < CONFIDENCE_THRESHOLDS.REQUEST_CLARIFICATION) {
    riskLevel = 'medium';
    warnings.push(`AI confidence is low (${Math.round(finalConfidence * 100)}%). Please verify the action components carefully.`);
  }

  // 2. Intent heuristics
  if (intent.type === 'unknown') {
    riskLevel = 'high';
    warnings.push('The intent parser could not confidently determine the action type.');
  }

  if (intent.ambiguities && intent.ambiguities.length > 0) {
    // Elevate risk if it's currently low, but don't overwrite a high risk
    if (riskLevel === 'low') riskLevel = 'medium';
    intent.ambiguities.forEach((ambiguity) => {
      warnings.push(`Parser ambiguity: ${ambiguity}`);
    });
  }

  // 3. Execution path heuristics
  if (steps.length === 0) {
    riskLevel = 'high';
    warnings.push('No execution steps were generated by the router.');
  }

  // 4. Future extensions (v2 - requires chain/indexer state)
  // - amount > 20% of wallet balance -> HIGH
  // - unverified token contract -> HIGH
  // - novel token pair / low liquidity -> HIGH
  // - first-time interaction with recipient -> MEDIUM

  return { riskLevel, warnings };
}
